name: antares-idl-k8s
description: Antares iDL Kubernetes resources
runtime:
    name: python
    options:
        virtualenv: venv
config:
    antares-idl-k8s:components.airbyte: true
    antares-idl-k8s:components.postgresql: true
    antares-idl-k8s:components.dagster: true
    antares-idl-k8s:components.efs-eks: true